name: bookshop_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  android_intent: ^2.0.0
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  firebase_storage: ^11.2.2
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  path_provider: ^2.0.15
  flutter_image_compress: ^2.0.3
  flutter_native_splash: ^2.2.19
  file_picker: ^5.3.1
  firebase_database: ^10.2.2
  google_sign_in: ^6.1.3
  firebase_messaging: ^14.6.2
  fluttertoast: ^8.2.2
  twitter_login: ^4.4.0
  flutter_facebook_auth: ^5.0.11
  twilio_flutter: ^0.0.9
  google_maps_flutter: ^2.3.0
  http: ^0.13.6
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.2.1+1
  get_it: ^7.6.0
  flutter_html: ^3.0.0-beta.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/book.jpg
    - assets/images/user.png
    - assets/images/book1.jpg
    - assets/images/book2.jpg
    - assets/images/book3.jpg
    - assets/images/book4.jpg
    - assets/images/book5.jpg
